# Generated by Django 5.2.6 on 2025-09-14 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='W2Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ein', models.CharField(blank=True, max_length=15, null=True)),
                ('ssn', models.CharField(blank=True, max_length=15, null=True)),
                ('wages', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('federal_tax_withheld', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pdf_file', models.FileField(upload_to='w2_pdfs/')),
                ('report_status', models.CharField(default='RECEIVED', max_length=50)),
                ('third_party_report_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
